CREATE DATABASE IF NOT EXISTS cdb_db; -- cdb for campus digital bookstore
 
USE cdb_db;

CREATE TABLE IF NOT EXISTS users (
    `UserId` INT AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(20) NOT NULL UNIQUE,
    `Email` VARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE IF NOT EXISTS `admin` (
    `AdminId` INT AUTO_INCREMENT PRIMARY KEY,
    `Name` VARCHAR(20) NOT NULL UNIQUE,
    `Email` VARCHAR(255) NOT NULL UNIQUE,
);

CREATE TABLE IF NOT EXISTS `book` (
    `BookId` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `Category` VARCHAR(255) NOT NULL,
    `Hash` VARCHAR(16) NOT NULL,
    `ISBN` VARCHAR(13) NOT NULL,
    `Amount` INT(11) UNSIGNED NOT NULL,
    `Publisher` VARCHAR(255) NOT NULL,
    `ReleaseDate` DATE NOT NULL,
    UNIQUE (`Hash`),
    UNIQUE (`ISBN`)
);

CREATE TABLE IF NOT EXISTS `title` (
    `TitleId` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `BookId` INT(11) UNSIGNED NOT NULL,
    `Language` VARCHAR(3) NOT NULL,
    FOREIGN KEY (`BookId`) REFERENCES `book`(`BookId`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `copy` (
    `CopyId` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `Hash` VARCHAR(16) NOT NULL,
    `OpenDate` DATE NOT NULL,
    `ExpireDate` DATE NOT NULL,
    `UserId` INT(11) UNSIGNED NOT NULL,
    FOREIGN KEY (`UserId`) REFERENCES `users`(`UserId`) ON DELETE CASCADE,
);
